#!bin/bash

# path to json file from task 0
JSON_FILE = "data.json"

#extraction usig jg

name=$(jq -r '.name' "$JSON_FILE" | sed 'sed 's/.*/\u&/')
height=$(jq -r '.height' "$JSON_FILE")
weight=$(jq -r '.weight' "$JSON_FILE")
type=$(jq -r '.types[0].type.name' "$JSON_FILE" | sed 's/.*/\u&/')

# Convert to meters and kg from decimeters/hectograms
height_m=$(awk "BEGIN {printf \"%.1f\", $height/10}")
weight_kg=$(awk "BEGIN {printf \"%.0f\", $weight/10}")

# Output in human-readable format
echo "$name is of type $type, weighs ${weight_kg}kg, and is ${height_m}m tall."
